version: '3'

services:

  ap-adminservice:
    build: adminservice
    image: sockyjam/apollo.adminservice:v01
    container_name: apollo.adminservice 
    environment:
            - SPRING_DATASOURCE_URL="jdbc:mysql://192.168.11.84:3308/apconfig?characterEncoding=utf8"
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=jfdaslghlklsfak78421k
    volumes:
            - ./admin_logs:/opt/logs
    ports:
      - "8090:8090"
    depends_on:
      - ap-mysql


  ap-configservice:
    build: configservice
    image: sockyjam/apollo.configservice:v01
    container_name: apollo.configservice
    environment:
            - SPRING_DATASOURCE_URL="jdbc:mysql://192.168.11.84:3308/apconfig?characterEncoding=utf8"
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=jfdaslghlklsfak78421k
    volumes:
            - ./config_logs:/opt/logs
    ports:
            - "8080:8080"
    depends_on:
      - ap-mysql



  ap-portal:
    build: portal
    image: sockyjam/apollo.portal
    container_name: apollo.portal
    environment:
            - SPRING_DATASOURCE_URL="jdbc:mysql://192.168.11.84:3308/apportal?characterEncoding=utf8"
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=jfdaslghlklsfak78421k
            - APOLLO_PORTAL_ENVS=dev,pro
              #- DEV_META=http://fill-in-dev-meta-server:8080
              #- PRO_META=http://fill-in-pro-meta-server:8080
    volumes:
            - ./portal_logs:/opt/logs
    ports:
            - "8070:8070"       
    depends_on:
      - ap-mysql

   

  ap-mysql:
    build: mysql
    image: sockyjam/apollo.mysql:v01
    container_name: apollo.mysql
    environment:
        MYSQL_ROOT_PASSWORD: "jfdaslghlklsfak78421k"
        MYSQL_DATABASE: "apollo_db"
        MYSQL_USER: "apollo"
        MYSQL_PASSWORD: "123456"
    volumes:
        - ./dbdata:/var/lib/mysql
    ports:
        - "3308:3306"
    expose:
        - "3306"
    command:
        --character-set-server=utf8
        --collation-server=utf8_general_ci

