FROM apolloconfig/apollo-configservice:1.7.0
MAINTAINER SockyJam <sockyjam@126.com>

#RUN export JAVA_OPTS="$JAVA_OPTS -Deureka.instance.ip-address=119.23.182.3 -Deureka.instance.prefer-ip-address=true -Dserver.port=8080"

EXPOSE 8080

