FROM apolloconfig/apollo-configservice:1.7.0
MAINTAINER SockyJam <sockyjam@126.com>

ADD startup.sh  /apollo-configservice/scripts/startup.sh
CMD ["/apollo-configservice/scripts/startup.sh"]

EXPOSE 8080

